---

################################################################################
#  description: Apply updates to Chrysus on CentOS7x
#  usage: ansible-playbook RHEL7x_Apply-Chrysus-Updates-playbook.yml --extra-vars 'HostOrGroup=YourServerOrGroupNameGoesHere'
#  author: Ernest G. Wilson II <ErnestGWilsonII@gmail.com> (https://github.com/ernestgwilsonii)
#  license: MIT
################################################################################


# Ansible Playbook options
# REF: http://docs.ansible.com/ansible/playbooks.html
#####################################################

- name: Apply updates to Chrysus on CentOS7x
  hosts: "{{ HostOrGroup|default ('FATAL ERROR --> HostOrGroup NOT SET! You must specify either a Host or a Group name!') }}"
  serial: "100%"
  gather_facts: False
  tasks:


# git - Deploy software (or files) from git checkouts
# REF: http://docs.ansible.com/ansible/git_module.html
######################################################

  - name: Git clone Chrysus to /opt/chrysus 
    git:
      repo: https://github.com/chrysus-io/chrysus.git
      dest: /opt/chrysus


# Use npm to install and manage Node.js packages
# REF: http://docs.ansible.com/ansible/npm_module.html
######################################################

  - name: Run npm install in /opt/chrysus
    npm:
      path: /opt/chrysus
      state: latest
      production: yes
      global: no


# Set attributes of files
# REF: http://docs.ansible.com/ansible/file_module.html
#######################################################

  - name: Set directory permisions on /opt/chrysus
    file:
      path: /opt/chrysus
      state: directory
      owner: chrysus
      group: wheel
      recurse: yes


# Restart the service
# REF: http://docs.ansible.com/ansible/service_module.html
##########################################################

  - name: Restart the chrysus service
    service:
      name=chrysus.service
      enabled=yes
      state=restarted
      # Note: Verify chrysus via SSH command line:
      # systemctl status chrysus
