---

################################################################################
#  description: Installs MongoDB 3x on CentOS7x
#  usage: ansible-playbook CentOS7x_Install-MongoDB-in-Stand-Alone-Mode-playbook.yml --extra-vars 'HostOrGroup=YourServerOrGroupNameGoesHere MongoAdminPassword=StartingAdminPasswordHere'
#  author: Ernest G. Wilson II <ErnestGWilsonII@gmail.com> (https://github.com/ernestgwilsonii)
#  license: MIT
################################################################################


# Ansible Playbook options
# REF: http://docs.ansible.com/ansible/playbooks.html
#####################################################

- name: Install MongoDB 3x on CentOS7x
  hosts: "{{ HostOrGroup|default ('FATAL ERROR --> HostOrGroup NOT SET! You must specify either a Host or a Group name!') }}"
  serial: "100%"
  gather_facts: False
  tasks:


# Install or configure repository used on the OS by yum
# REF: https://docs.ansible.com/ansible/yum_repository_module.html
##################################################################

# /etc/yum.repos.d/mongodb-org-3.4.repo
  - name: Install repository for MongoDB Community Edition
    yum_repository:
      name: MongoDB
      description: MongoDB Repository
      file: mongodb-org-3.4
      baseurl: https://repo.mongodb.org/yum/redhat/$releasever/mongodb-org/3.4/x86_64/
      enabled: yes
      gpgcheck: yes
      gpgkey: https://www.mongodb.org/static/pgp/server-3.4.asc


# Install yum packages
# REF: http://docs.ansible.com/ansible/yum_module.html
######################################################

  - name: Install mongodb-org
    yum:
      name=mongodb-org
      state=latest


# Update various configuration files
# REF: http://docs.ansible.com/ansible/lineinfile_module.html
#############################################################

  - name: Ensure that boot-time transparent_hugepage/defrag is set to never
    lineinfile:
      dest=/etc/rc.local
      state=present
      line='echo never > /sys/kernel/mm/transparent_hugepage/defrag'

  - name: Ensure that boot-time transparent_hugepage/enabled is set to never
    lineinfile:
      dest=/etc/rc.local
      state=present
      line='echo never > /sys/kernel/mm/transparent_hugepage/enabled'


# Use the file module
# REF: http://docs.ansible.com/ansible/file_module.html
#######################################################

# /etc/rc.local is linked to /etc/rc.d/rc.local which must be set executable
  - name: chmod 777 /etc/rc.d/rc.local
    file:
      path: /etc/rc.d/rc.local
      mode: 0777


# command - Executes a command on a remote node
# REF: http://docs.ansible.com/ansible/command_module.html
##########################################################

  - name: Ensure current active running value transparent_hugepage/defrag is set to never
    command: echo never > /sys/kernel/mm/transparent_hugepage/defrag

  - name: Ensure current active running value transparent_hugepage/enabled is set to never
    command: echo never > /sys/kernel/mm/transparent_hugepage/enabled


# Restart firewalld to make sure it is running OK before changing any rules
# REF: http://docs.ansible.com/ansible/service_module.html
##########################################################

  - name: Ensure the firewalld service is enabled and re-started before changing any rules
    service:
      name=firewalld
      enabled=yes
      state=restarted


# Update the firewalld configuration
# REF: http://docs.ansible.com/ansible/firewalld_module.html
############################################################

  - name: Update firewall to allow port TCP 27017 for incoming MongoDB connections
    firewalld:
      port=27017/tcp
      permanent=true
      immediate=yes
      state=enabled
      zone=public


# Tweak settings in INI files
# REF: http://docs.ansible.com/ansible/ini_file_module.html
###########################################################

# Set values in /usr/lib/systemd/system/mongod.service
  - name: Specify After value of multi-user.target under the Unit section in /usr/lib/systemd/system/mongod.service
    ini_file:
      dest: /usr/lib/systemd/system/mongod.service
      section: Unit
      option: After
      value: 'multi-user.target'

# Set values in /usr/lib/systemd/system/mongod.service
  - name: Remove the WantedBy value of multi-user.target under the Install section in /usr/lib/systemd/system/mongod.service
    ini_file:
      dest: /usr/lib/systemd/system/mongod.service
      section: Install
      option: WantedBy
      state: absent


# Use the copy module to copy various files into place
# REF: http://docs.ansible.com/ansible/copy_module.html
#######################################################

# /usr/lib/tmpfiles.d/mongod.conf
  - name: Copy the mongod.conf systemd tmpfiles.d configuration file from Ansible local file files/MongoDB/mongod.conf to MongoDB remote /usr/lib/tmpfiles.d/mongod.conf
    copy:
      src=files/MongoDB/mongod.conf
      dest=/usr/lib/tmpfiles.d/mongod.conf
      owner=mongod
      group=mongod
      mode=0644


# Enable and start mongod service
# REF: http://docs.ansible.com/ansible/service_module.html
##########################################################

  - name: Enable and start the mongod service for the first time with the default configuration
    service:
      name=mongod.service
      enabled=yes
      state=restarted
      # Note: Command line verification:
      # systemctl status mongod.service
      # systemctl status mongod.service -l
      # service mongod status
      # ls /var/lib/mongo
      # cat /var/log/messages | grep mongod
      # cat /usr/lib/systemd/system/mongod.service
      # cat /etc/mongod.conf
      # cat /var/log/mongodb/mongod.log


# Use the template module to populate files with data
# REF: http://docs.ansible.com/ansible/template_module.html
###########################################################

# An "import" JS file will be used to create the initial starting admin user and set a starting password
  - name: Copy a "MongoDB style JS import template" file needed to create the initial admin account 
    template:
      src=templates/MongoDB/addMongoAdmin.js.j2
      dest=/tmp/addMongoAdmin.js
      owner=root
      group=mongod
      mode=0644

# /etc/mongod.conf - Enables security flag that requires usernames/passwords going forward
  - name: Deploy modified production ready configuration templates/MongoDB/stand-alone-mode-mongod.conf.j2 to remote /etc/mongod.conf
    template:
      src=templates/MongoDB/stand-alone-mode-mongod.conf.j2
      dest=/etc/mongod.conf
      owner=root
      group=mongod
      mode=0644


# Execute raw command(s)
# REF: http://docs.ansible.com/ansible/raw_module.html
##########################################################

# Add a starting admin user and starting password to the "admin" database BEFORE security gets enabled!
  - name: Create a starting "admin" user and setting the starting password to {{ MongoAdminPassword|default ('mongodb') }}
    raw: /usr/bin/mongo admin < /tmp/addMongoAdmin.js


# Use the file module
# REF: http://docs.ansible.com/ansible/file_module.html
#######################################################

  - name: rm /tmp/addMongoAdmin.js
    file:
      path: /tmp/addMongoAdmin.js
      state: absent


# Use the copy module to copy various files into place
# REF: http://docs.ansible.com/ansible/copy_module.html
#######################################################

# /etc/ssl/mongodb.pem
  - name: Copy starting self-signed certificate from Ansible files/MongoDB/mongodb.pem to MongoDB remote /etc/ssl/mongodb.pem
    copy:
      src=files/MongoDB/mongodb.pem
      dest=/etc/ssl/mongodb.pem
      owner=mongod
      group=mongod
      mode=0400


# command - Executes a command on a remote node
# REF: http://docs.ansible.com/ansible/command_module.html
##########################################################

  - name: Ensure current active running value transparent_hugepage/defrag is set to never
    command: echo never > /sys/kernel/mm/transparent_hugepage/defrag

  - name: Ensure current active running value transparent_hugepage/enabled is set to never
    command: echo never > /sys/kernel/mm/transparent_hugepage/enabled


# Re-start mongod service
# REF: http://docs.ansible.com/ansible/service_module.html
##########################################################

  - name: Re-start the mongod service with a production ready configuration in place
    service:
      name=mongod.service
      enabled=yes
      state=restarted
      # Note: Command line verification:
      # systemctl status mongod.service
      # systemctl status mongod.service -l
      # service mongod status
      # ls /var/lib/mongo
      # cat /var/log/messages | grep mongod
      # cat /usr/lib/systemd/system/mongod.service
      # cat /etc/mongod.conf
      # cat /var/log/mongodb/mongod.log
