---

################################################################################
#  description: Uninstalls demon_checkForTeamUpdates on CentOS7x
#  usage: ansible-playbook CentOS7x_Uninstall-Demon-checkForTeamUpdates-playbook.yml --extra-vars 'HostOrGroup=YourServerOrGroupNameGoesHere'
#  author: Ernest G. Wilson II <ErnestGWilsonII@gmail.com> (https://github.com/ernestgwilsonii)
#  license: MIT
################################################################################


# Ansible Playbook options
# REF: http://docs.ansible.com/ansible/playbooks.html
#####################################################

- name: Uninstall demon_checkForTeamUpdates on CentOS7x
  hosts: "{{ HostOrGroup|default ('FATAL ERROR --> HostOrGroup NOT SET! You must specify either a Host or a Group name!') }}"
  serial: "100%"
  gather_facts: False
  tasks:


# service - Manage services
# REF: http://docs.ansible.com/ansible/service_module.html
##########################################################

  - name: Stop and disable the systemctl demon_checkForTeamUpdates service
    service:
      name: demon_checkForTeamUpdates
      enabled: no
      state: stopped


# file - Sets attributes of files and folders
# REF: http://docs.ansible.com/ansible/file_module.html
#######################################################

# /opt/demon_checkForTeamUpdates
  - name: Delete /opt/demon_checkForTeamUpdates
    file:
      path: /opt/demon_checkForTeamUpdates
      state: absent

# /etc/systemd/system/demon_checkForTeamUpdates.service
  - name: Delete systemctl service file /etc/systemd/system/demon_checkForTeamUpdates.service
    file:
      path: /etc/systemd/system/demon_checkForTeamUpdates.service
      state: absent


# raw - Executes a low-down and dirty SSH command
# REF: http://docs.ansible.com/ansible/raw_module.html
######################################################

  - name: systemctl daemon-reload
    shell: systemctl daemon-reload
