---

################################################################################
#  description: Stop updating OS Kernel 3x on CentOS7x
#  usage: ansible-playbook CentOS7x_Stop-Updating-Kernel3x-playbook.yml --extra-vars 'HostOrGroup=YourServerOrGroupNameGoesHere'
#  author: Ernest G. Wilson II <ErnestGWilsonII@gmail.com> (https://github.com/ernestgwilsonii)
#  license: MIT
################################################################################


# Ansible Playbook options
# REF: http://docs.ansible.com/ansible/playbooks.html
#####################################################

- name: Stop updating OS Kernel 3x on CentOS7x
  hosts: "{{ HostOrGroup|default ('FATAL ERROR --> HostOrGroup NOT SET! You must specify either a Host or a Group name!') }}"
  serial: "100%"
  gather_facts: False
  tasks:


# Update various configuration files
# REF: http://docs.ansible.com/ansible/lineinfile_module.html
#############################################################

  - name: Make sure /etc/yum.conf has exclude=kernel-3*
    lineinfile:
      dest=/etc/yum.conf
      state=present
      line='exclude=kernel-3*'

  - name: Make sure /etc/yum.conf has exclude=kernel-headers-3*
    lineinfile:
      dest=/etc/yum.conf
      state=present
      line='exclude=kernel-headers-3*'

  - name: Make sure /etc/yum.conf has exclude=kernel-tools-3*
    lineinfile:
      dest=/etc/yum.conf
      state=present
      line='exclude=kernel-tools-3*'

  - name: Make sure /etc/yum.conf has exclude=kernel-tools-libs-3*
    lineinfile:
      dest=/etc/yum.conf
      state=present
      line='exclude=kernel-tools-libs-3*'

  - name: Make sure /etc/yum.conf has installonly_limit=3
    lineinfile:
      dest=/etc/yum.conf
      state=present
      line='installonly_limit=3'
