---

################################################################################
#  description: Configures CentOS7x OS with Ansible
#  usage: ansible-playbook CentOS7x_MASTER-Basic-OS-with-Ansible-playbook.yml --extra-vars 'HostOrGroup=YourServerOrGroupNameGoesHere'
#  author: Ernest G. Wilson II <ErnestGWilsonII@gmail.com> (https://github.com/ernestgwilsonii)
#  license: MIT
################################################################################


# Include specific / desired Ansible Playbooks
# REF: http://docs.ansible.com/ansible/playbooks_roles.html
###########################################################

# Basic OS items included on every CentOS7x installation
- include: CentOS7x_Apply-OS-Updates-playbook.yml
- include: CentOS7x_Install-Basic-Utilities-playbook.yml

# Included if Ansible services is desired
- include: CentOS7x_Install-Ansible-playbook.yml
