---

################################################################################
#  description: Installs Kubernetes on CentOS7x
#  usage: ansible-playbook CentOS7x_Install-Kubernetes-playbook.yml --extra-vars 'HostOrGroup=YourServerOrGroupNameGoesHere'
#  author: Ernest G. Wilson II <ErnestGWilsonII@gmail.com> (https://github.com/ernestgwilsonii)
#  license: MIT
################################################################################


# Ansible Playbook options
# REF: http://docs.ansible.com/ansible/playbooks.html
#####################################################

- name: Install Kubernetes on CentOS7x
  hosts: "{{ HostOrGroup|default ('FATAL ERROR --> HostOrGroup NOT SET! You must specify either a Host or a Group name!') }}"
  serial: "100%"
  gather_facts: False
  tasks:


# Install or configure repository used on the OS by yum
# REF: https://docs.ansible.com/ansible/yum_repository_module.html
##################################################################

# /etc/yum.repos.d/kubelet.repo
  - name: Install repository kubelet
    yum_repository:
      name: kubelet
      description: Kubernetes Repository
      file: kubelet
      baseurl: http://files.rm-rf.ca/rpms/kubelet/
      enabled: yes
      gpgcheck: no


# Install yum packages
# REF: http://docs.ansible.com/ansible/yum_module.html
######################################################

  - name: Install bind-utils
    yum:
      name: bind-utils
      state: latest

# https://github.com/docker/docker/releases
  - name: Install docker-engine
    yum:
      name: docker-engine
      state: latest

  - name: Install git
    yum:
      name: git
      state: latest

  - name: Install jq
    yum:
      name: jq
      state: latest

# https://lukemarsden.github.io/docs/getting-started-guides/kubeadm/
  - name: Install kubelet
    yum:
      name: kubelet
      state: latest

  - name: Install kubeadm
    yum:
      name: kubeadm
      state: latest

  - name: Install kubectl
    yum:
      name: kubectl
      state: latest

  - name: Install kubernetes-cni
    yum:
      name: kubernetes-cni
      state: latest


# Restart firewalld to make sure it is running OK before changing any rules
# REF: http://docs.ansible.com/ansible/service_module.html
##########################################################

  - name: Ensure the firewalld service is enabled and re-started before changing any rules
    service:
      name: firewalld
      enabled: yes
      state: restarted


# Update the firewalld configuration
# REF: http://docs.ansible.com/ansible/firewalld_module.html
############################################################

  - name: Update firewall to allow port UDP 53 for incoming connections
    firewalld:
      port: 53/udp
      permanent: true
      immediate: yes
      state: enabled
      zone: public

  - name: Update firewall to allow port TCP 53 for incoming connections
    firewalld:
      port: 53/tcp
      permanent: true
      immediate: yes
      state: enabled
      zone: public

  - name: Update firewall to allow port TCP 80 for incoming connections
    firewalld:
      port: 80/tcp
      permanent: true
      immediate: yes
      state: enabled
      zone: public

  - name: Update firewall to allow port TCP 6443 for incoming Kubernetes API connections
    firewalld:
      port: 6443/tcp
      permanent: true
      immediate: yes
      state: enabled
      zone: public

  - name: Update firewall to allow port TCP 9898 for incoming Kubernetes Discovery connections
    firewalld:
      port: 9898/tcp
      permanent: true
      immediate: yes
      state: enabled
      zone: public

  - name: Update firewall to allow port TCP 10250 for incoming connections
    firewalld:
      port: 10250/tcp
      permanent: true
      immediate: yes
      state: enabled
      zone: public

  - name: Update firewall to allow port TCP 15441 for incoming connections
    firewalld:
      port: 15441/tcp
      permanent: true
      immediate: yes
      state: enabled
      zone: public

  - name: Update firewall to allow port TCP 31869 for incoming connections
    firewalld:
      port: 31869/tcp
      permanent: true
      immediate: yes
      state: enabled
      zone: public


# Enable and start kubelet
# REF: http://docs.ansible.com/ansible/service_module.html
##########################################################

  - name: Enable and start (or restart) the kubelet service
    service:
      name: kubelet
      enabled: yes
      state: restarted
      # Note: Verify kubelet via SSH command line:
      # systemctl status kubelet
