---

################################################################################
#  description: Install a comfortable CentOS7x workstation
#  usage: ansible-playbook CentOS7x_MASTER-Install-Workstation-playbook.yml --extra-vars 'HostOrGroup=YourServerOrGroupNameGoesHere'
#  author: Ernest G. Wilson II <ErnestGWilsonII@gmail.com> (https://github.com/ernestgwilsonii)
#  license: MIT
################################################################################


# Include specific / desired Ansible Playbooks
# REF: http://docs.ansible.com/ansible/playbooks_roles.html
###########################################################

# Basic OS items included on every CentOS7x installation
- include: CentOS7x_Apply-OS-Updates-playbook.yml
- include: CentOS7x_Install-NTP-Services-playbook.yml
- include: CentOS7x_Install-Basic-Utilities-playbook.yml

# Include Java8x JRE and SDK
- include: CentOS7x_Install-Java8x-playbook.yml

# Include Ansible services
- include: CentOS7x_Install-Ansible-playbook.yml

# Include Docker services
- include: CentOS7x_Install-Docker-playbook.yml

# Include RDP services
- include: CentOS7x_Install-RDP-Services-playbook.yml
