---

################################################################################
#  description: Installs RDP Services on CentOS7x
#  usage: ansible-playbook CentOS7x_Install-RDP-Services-playbook.yml --extra-vars 'HostOrGroup=YourServerOrGroupNameGoesHere'
#  author: Ernest G. Wilson II <ErnestGWilsonII@gmail.com> (https://github.com/ernestgwilsonii)
#  license: MIT
################################################################################


# Ansible Playbook options
# REF: http://docs.ansible.com/ansible/playbooks.html
#####################################################

- name: Install RDP Services on CentOS7x
  hosts: "{{ HostOrGroup|default ('FATAL ERROR --> HostOrGroup NOT SET! You must specify either a Host or a Group name!') }}"
  serial: "100%"
  gather_facts: False
  tasks:


# Install or configure repository used on the OS by yum
# REF: https://docs.ansible.com/ansible/yum_repository_module.html
##################################################################

# /etc/yum.repos.d/vscode.repo
# https://code.visualstudio.com/docs/setup/linux
  - name: Install repository Visual Studio Code
    yum_repository:
      name: vscode
      description: Visual Studio Code
      file: vscode
      baseurl: https://packages.microsoft.com/yumrepos/vscode
      enabled: yes
      gpgcheck: yes
      gpgkey: https://packages.microsoft.com/keys/microsoft.asc


# Install yum packages
# REF: http://docs.ansible.com/ansible/yum_module.html
######################################################

  - name: Install Server with GUI group packages
    yum:
      name="@^Server with GUI"
      state=present
      # Note: RHEL7x has two (2) types of group lists "package groups" and "environment groups"
      # Use: yum group list
      # REF: http://docs.ansible.com/ansible/yum_module.html#notes

  - name: Install the xrdp package
    yum:
      name=xrdp
      state=latest

  - name: Install the tigervnc-server package
    yum:
      name=tigervnc-server
      state=latest

  - name: Install the Microsoft Visual Studio Code
    yum:
      name: code
      state: present


# Restart firewalld to make sure it is running OK before changing any rules
# REF: http://docs.ansible.com/ansible/service_module.html
##########################################################

  # - name: Ensure the firewalld service is enabled and re-started before changing any rules
  #   service:
  #     name=firewalld
  #     enabled=yes
  #     state=restarted


# Update the firewalld configuration
# REF: http://docs.ansible.com/ansible/firewalld_module.html
############################################################

  - name: Update firewall to allow port TCP 3389 for incoming RDP connections
    firewalld:
      port=3389/tcp
      permanent=true
      immediate=yes
      state=enabled
      zone=public


# Enable and start xrdp.service
# REF: http://docs.ansible.com/ansible/service_module.html
##########################################################

  - name: Enable and start the xrdp.service service
    service:
      name=xrdp.service
      enabled=yes
      state=restarted


# Execute command(s)
# REF: http://docs.ansible.com/ansible/command_module.html
##########################################################

  - name: /usr/libexec/iptables/iptables.init save
    command: /usr/libexec/iptables/iptables.init save
    #cat /etc/sysconfig/iptables
