---

################################################################################
#  description: Installs opensource Java 1.8x on RHEL7x
#  usage: ansible-playbook RHEL7x_Install-Java8x-playbook.yml --extra-vars 'HostOrGroup=YourServerOrGroupNameGoesHere'
#  author: Ernest G. Wilson II <ErnestGWilsonII@gmail.com> (https://github.com/ernestgwilsonii)
#  license: MIT
################################################################################


# Ansible Playbook options
# REF: http://docs.ansible.com/ansible/playbooks.html
#####################################################

- name: Install opensource Java 1.8x on RHEL7x
  hosts: "{{ HostOrGroup|default ('FATAL ERROR --> HostOrGroup NOT SET! You must specify either a Host or a Group name!') }}"
  serial: "100%"
  gather_facts: False
  tasks:


# Install yum packages
# REF: http://docs.ansible.com/ansible/yum_module.html
######################################################

  - name: Install the Java JRE runtime java
    yum:
      name=java-1.8.0-openjdk
      state=latest

  - name: Install the Java JDK compiler javac
    yum:
      name=java-1.8.0-openjdk-devel
      state=latest


# Update various configuration files
# REF: http://docs.ansible.com/ansible/lineinfile_module.html
#############################################################

  - name: Set JAVA_HOME environment variable for root on next login
    lineinfile:
      dest=/root/.bash_profile
      state=present
      line='export JAVA_HOME=/usr/lib/jvm/java-openjdk'

  - name: Set JRE_HOME environment variable for root on next login
    lineinfile:
      dest=/root/.bash_profile
      state=present
      line='export JRE_HOME=/usr/lib/jvm/java-openjdk/jre'

  - name: Add Java to the path for root on next login
    lineinfile:
      dest=/root/.bash_profile
      state=present
      line='export PATH=$PATH:/usr/lib/jvm/java-openjdk/bin:/usr/lib/jvm/java-openjdk/jre/bin'
