---

################################################################################
#  description: Updates mongoDB on RHEL7x
#  usage: ansible-playbook RHEL7x_Apply-mongoDB-Updates-playbook.yml --extra-vars 'HostOrGroup=YourServerOrGroupNameGoesHere'
#  author: Ernest G. Wilson II <ErnestGWilsonII@gmail.com> (https://github.com/ernestgwilsonii)
#  license: MIT
################################################################################


# Ansible Playbook options
# REF: http://docs.ansible.com/ansible/playbooks.html
#####################################################

- name: Update mongoDB on RHEL7x
  hosts: "{{ HostOrGroup|default ('FATAL ERROR --> HostOrGroup NOT SET! You must specify either a Host or a Group name!') }}"
  serial: "100%"
  gather_facts: False
  tasks:


# Install yum packages (listed in alphabetical order)
# REF: http://docs.ansible.com/ansible/yum_module.html
######################################################

  - name: Update mongoDB
    yum:
      name=mongodb-org
      state=latest


# Restart mongod.service
# REF: http://docs.ansible.com/ansible/service_module.html
##########################################################

  - name: Ensure the mongod.service service is enabled and restarted
    service:
      name=mongod.service
      enabled=yes
      state=restarted
