---

################################################################################
#  description: Updates Elasticsearch on RHEL7x
#  usage: ansible-playbook RHEL7x_Apply-Elasticsearch-Updates-playbook.yml --extra-vars 'HostOrGroup=YourServerOrGroupNameGoesHere'
#  author: Ernest G. Wilson II <ErnestGWilsonII@gmail.com> (https://github.com/ernestgwilsonii)
#  license: MIT
################################################################################


# Ansible Playbook options
# REF: http://docs.ansible.com/ansible/playbooks.html
#####################################################

- name: Update Elasticsearch on RHEL7x
  hosts: "{{ HostOrGroup|default ('FATAL ERROR --> HostOrGroup NOT SET! You must specify either a Host or a Group name!') }}"
  serial: "100%"
  gather_facts: False
  tasks:


# Install yum packages (listed in alphabetical order)
# REF: http://docs.ansible.com/ansible/yum_module.html
######################################################

  - name: Update Elasticsearch
    yum:
      name=elasticsearch
      state=latest


# Restart elasticsearch.service
# REF: http://docs.ansible.com/ansible/service_module.html
##########################################################

  - name: Ensure the elasticsearch.service is enabled and restarted
    service:
      name=elasticsearch.service
      enabled=yes
      state=restarted
