version: '3.4'

services:

  portainer:
    image: portainer/portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - type: bind
        source: /opt/portainer
        target: /data
    ports:
      - 9000:9000
    networks:
      - portainer-net1
    deploy:
      placement:
        constraints:
          - node.labels.swarm.node == 1
          - node.role == manager
      labels:
        local.description: "Portainer"

networks:
  portainer-net1: