---

################################################################################
#  description: Add iptables rules to the swarm for Portainer
#  usage: ansible-playbook Docker-Compose_Swarm_Portainer-playbook.yml --extra-vars 'HostOrGroup=Swarm1'
#  author: Ernest G. Wilson II <ErnestGWilsonII@gmail.com> (https://github.com/ernestgwilsonii)
#  license: MIT
################################################################################


# Ansible Playbook options
# REF: http://docs.ansible.com/ansible/playbooks.html
#####################################################

- name: Add iptables firewall rules to the swarm
  hosts: "{{ HostOrGroup|default ('Swarm1') }}"
  serial: "100%"
  gather_facts: False
  tasks:


# iptables - Modify the systems iptables
# REF: http://docs.ansible.com/ansible/latest/iptables_module.html
##################################################################

  - name: Update iptables to allow port TCP 9000 for incoming Docker Portainer connections
    iptables:
      chain: INPUT
      ctstate: NEW,ESTABLISHED,RELATED
      protocol: tcp
      match: tcp
      destination_port: 9000
      comment: Allow port TCP 9000 for incoming Docker Portainer connections
      jump: ACCEPT
      state: present
    become: yes


# Execute command(s)
# REF: http://docs.ansible.com/ansible/command_module.html
##########################################################

  - name: /usr/libexec/iptables/iptables.init save
    command: /usr/libexec/iptables/iptables.init save
    # cat /etc/sysconfig/iptables
