version: '3.4'

services:

  visualizer:
    image: dockersamples/visualizer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8080:8080
    networks:
      - visualizer-net1
    deploy:
      placement:
        constraints: [node.role == manager]
      labels:
        local.description: "Visualizer"

networks:
  visualizer-net1: